### ISSUE TITLE
Possible undesired null byte ignorance

### ISSUE THREAD

**Issue by pitrp** [eworm-de/cgit#1]
https://github.com/eworm-de/cgit/blob/adcc4f822fe11836e5f942fc1ae0f00db4eb8d5f/html.c#L62

It looks like the check should be (len >= ...) to avoid loosing a null byte.

Since I have not looked at the actual fmt() uses, ignoring the null byte might be fine.
But the following message talks about "string", so this hint seems justified.

**Comment by eworm-de** [comment]
Sent upstream, you should have received a mail. Thanks!
